# netlify.toml

# --- Configuración de Construcción Principal ---
[build]
  # Comando para construir la aplicación de Angular.
  # Se ejecuta desde el directorio 'base' que se especifica abajo.
  command = "ng build"

  # Directorio donde Angular deja los archivos compilados (relativo a la raíz del proyecto).
  publish = "creedme-angular/dist/creedme-angular/browser"

  # Directorio de las funciones (relativo a la raíz del repositorio).
  functions = "netlify/functions"

# --- Contexto de Construcción para el Frontend ---
# Le decimos a Netlify que entre en esta carpeta antes de ejecutar el 'command'.
[context.production]
  base = "creedme-angular"

[context.deploy-preview]
  base = "creedme-angular"

[context.branch-deploy]
  base = "creedme-angular"

# --- Configuración de Funciones ---
[functions]
  [functions."processSet"]
    timeout = 26

# --- Redirección para Single Page Apps (SPA) ---
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200