# netlify.toml

[build]
  # Directorio donde se encuentran las Netlify Functions
  functions = "netlify/functions"
  # Comando para compilar el proyecto de Angular
  command = "ng build --prod"
  # Directorio de salida después de la compilación
  publish = "creedme-angular/dist/creedme-angular/browser"

[functions]
  # Aumenta el tiempo de espera para funciones específicas
  [functions."processSet"]
    timeout = 26

# Redirección para que las Single Page Applications (SPA) como Angular funcionen correctamente
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
