# netlify.toml (Versión Final, Simplificada y Robusta)

[build]
  # 1. Comando: Se ejecuta desde la raíz. Entra a la carpeta de Angular,
  #    instala sus dependencias y luego construye el proyecto.
  command = "cd creedme-angular && npm install && ng build"

  # 2. Funciones: Ruta a las funciones, desde la raíz.
  functions = "netlify/functions"

  # 3. Publicación: Ruta a los archivos compilados, desde la raíz.
  #    Esta es la corrección clave. Apunta a la carpeta que el log nos dice que se está creando.
  publish = "creedme-angular/dist/creedme-angular/"

# --- Configuración de Funciones ---
[functions]
  [functions."processSet"]
    timeout = 26

# --- Redirección para la SPA de Angular ---
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200