# netlify.toml (Versión Final Definitiva)

[build]
  # 1. Base: Le decimos a Netlify que este es nuestro directorio de trabajo principal.
  # Netlify entrará aquí y ejecutará 'npm install' automáticamente.
  base = "creedme-angular"

  # 2. Comando: Ejecutamos el script "build" del package.json de Angular.
  # Esto usará la versión local de 'ng' que se acaba de instalar en node_modules.
  command = "npm run build"

  # 3. Publicación: La ruta es ahora RELATIVA a la 'base'.
  # El resultado de la compilación estará en 'dist/creedme-angular/'.
  publish = "dist/creedme-angular/browser"

  # 4. Funciones: Esta ruta debe ser desde la RAÍZ del repositorio.
  functions = "netlify/functions"

# --- Configuración de Funciones ---
[functions]
  [functions."processSet"]
    timeout = 26

# --- Redirección para la SPA de Angular ---
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200