# netlify.toml (Versión Final - Siguiendo la recomendación de Netlify)

# --- Configuración de Construcción ---
[build]
  # Directorio base para la construcción. Netlify entrará aquí y ejecutará 'npm install'.
  base = "creedme-angular"

  # Comando que se ejecuta DESPUÉS de instalar las dependencias en 'base'.
  # 'npm run build' ejecutará el script "build": "ng build" de tu package.json de Angular.
  command = "npm run build"

  # Directorio de publicación (relativo a la raíz del repositorio).
  publish = "creedme-angular/dist/creedme-angular/browser"

  # Directorio de las funciones (relativo a la raíz del repositorio).
  functions = "netlify/functions"

# --- Configuración de Funciones ---
[functions]
  [functions."processSet"]
    timeout = 26

# --- Redirección para la SPA de Angular ---
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200