[build]
  # Ejecuta el script 'build' que definimos en package.json
  command = "npm run build"

  # Ruta exacta donde Angular dejará el index.html
  # Estructura: carpeta_frontend / dist / nombre_proyecto / browser
  publish = "frontend/dist/creedme-angular/browser"

  # Ruta donde están tus funciones de backend
  functions = "netlify/functions"

[functions]
  # Configuración para evitar timeouts en la función pesada
  [functions."processSet"]
    timeout = 26