# netlify.toml (Versión Final y Correcta)

# --- Configuración de Construcción Global ---
[build]
  # Comando que se ejecuta desde la raíz del repositorio.
  # Le decimos que entre a la carpeta de angular Y LUEGO ejecute ng build.
  command = "cd creedme-angular && ng build"

  # Directorio de las funciones (desde la raíz).
  functions = "netlify/functions"

  # Directorio de publicación de los archivos compilados (desde la raíz).
  publish = "creedme-angular/dist/creedme-angular/browser"

# --- Configuración de Funciones ---
[functions]
  [functions."processSet"]
    timeout = 26

# --- Redirección para la SPA de Angular ---
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200